### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by adadychanka** [KyzAlexander/DiplomReact#1]
Можно добавить `React.memo` для того, чтобы компонент лишний раз не рендерился. Актуально и для остальных компонентов в приложении.

https://github.com/KyzAlexander/DiplomReact/blob/28f87820cf492c4ac530646d62cff578cd0b62f8/src/components/cardRepository.js#L31
---
Название компонента не соответствует тому, что он отрисовывает. Можно сделать два отдельных компонента `RepositoryList` и `RepositoryCard`. В `RepositoryList` будет рендериться `RepositoryCard` на каждый элемент массива. 
https://github.com/KyzAlexander/DiplomReact/blob/28f87820cf492c4ac530646d62cff578cd0b62f8/src/components/cardRepository.js#L3

---
Можно добавить больше семантики применив `ul` и `li` элементы.
https://github.com/KyzAlexander/DiplomReact/blob/28f87820cf492c4ac530646d62cff578cd0b62f8/src/components/cardRepository.js#L28

---

**Comment by KyzAlexander** [comment]
Посмотри, пожалуйста, так ли я исправил замечания ?
